### ISSUE TITLE
Version 1.3.0 is so slow

### ISSUE THREAD

**Issue by jorgecasar** [folke/vscode-monorepo-workspace#78]
In a project with more than 50 packages and thousand of dependencies the new version 1.3.0 take long time to launch "Select workspace Folders". I downgraded to 1.2.0 and the process is instantaneous.

**Comment by folke** [comment]
That is really odd. The new build should actually be a tiny bit faster, since the extension code is now bundled :)

I've just tested this with https://github.com/pnpm/pnpm, that has about 98 packages, and the popup to select workspace folders opens instantly.

Can you see if the slowdown happens on your end with the pnpm project?

I assume you're working on a private repo?

What monorepo tool do you use? Yarn, Lerna, ...?

**Comment by jorgecasar** [comment]
It should be something with my repo I tried in others and works fine. I don't know why it works fine in 1.2.0.

In the version 1.3.0 it also take all packages inside node_modules to select. Is that correct?

**Comment by ckot** [comment]
@jorgecasar I discovered that while v1.2 didn't have the behavior, v1.3 doesn't list what's in a packages node_modules if the package contains a .gitignore telling it to ignore node_modules.  I wonder if this is what's causing the slowdown with your repo.   either that, or perhaps the top-level .gitignore needs a better glob for maching any node_modules folder within the monorepo

**Comment by folke** [comment]
Should be fixed in the last release.
